# Generated by Django 2.2.1 on 2020-03-13 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_examplemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examplemodel',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
